# Generated by Django 4.2.7 on 2025-03-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launderer', '0002_laundryitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaundryItem',
        ),
    ]
