# Generated by Django 4.2.7 on 2025-03-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launderer', '0003_delete_laundryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundererpaymentmethod',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='laundererpaymentmethod',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='laundererpaymentmethod',
            name='ifsc_code',
        ),
        migrations.AlterField(
            model_name='laundererpaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash on Delivery')], max_length=10),
        ),
    ]
