# Generated by Django 4.2.7 on 2025-03-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_launderer_max_orders_per_day_order_delivery_slot_and_more'),
        ('launderer', '0004_remove_laundererpaymentmethod_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laundererorderstatus',
            options={},
        ),
        migrations.RenameField(
            model_name='laundererservice',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='laundererpaymentmethod',
            name='account_number_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of account', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='laundererpaymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laundererpaymentmethod',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='MM/YYYY format', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='laundererpaymentmethod',
            name='card_name',
            field=models.CharField(blank=True, help_text='Name on the card', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laundererpaymentmethod',
            name='card_number_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='laundererpaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='laundererworkinghour',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterUniqueTogether(
            name='laundererpaymentmethod',
            unique_together={('launderer', 'payment_type')},
        ),
    ]
