# Generated by Django 4.2.7 on 2025-03-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundererverification',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='verification/address_proofs/'),
        ),
        migrations.AddField(
            model_name='laundererverification',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='verification/business_licenses/'),
        ),
        migrations.AddField(
            model_name='laundererverification',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='verification/id_proofs/'),
        ),
    ]
