# Generated by Django 4.2.7 on 2025-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_contactmessage_admin_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash on Delivery')], max_length=20),
        ),
    ]
