# Generated by Django 4.2.7 on 2025-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothitem',
            name='service_type',
            field=models.CharField(blank=True, help_text='Specific service type this item is available for', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='launderer',
            name='base_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='launderer',
            name='delivery_radius',
            field=models.PositiveIntegerField(default=5, help_text='Maximum delivery radius in kilometers'),
        ),
        migrations.AddField(
            model_name='launderer',
            name='min_order_free_delivery',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Minimum order amount for free delivery', max_digits=8),
        ),
        migrations.AddField(
            model_name='launderer',
            name='per_km_charge',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Distance in kilometers', max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
