# Generated by Django 4.2.7 on 2025-03-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_clothitem_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='launderer',
            name='provides_delivery',
            field=models.BooleanField(default=True, help_text='Whether this launderer provides delivery services'),
        ),
    ]
