# Generated by Django 4.2.7 on 2025-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('processing', 'Processing'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_acceptance', max_length=20),
        ),
    ]
